Main/Areas/Admin/Controllers/BlogManagerController.cs
using Main.Models.Domain;
using Main.Models.ViewModels;
using Main.Repos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Main.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/[controller]/[action]")]
    [Authorize(Roles = "Admin, Head Admin")]
    public class BlogManagerController : Controller
    {
        private readonly ITagRepo tagRepo;
        private readonly IBlogPostRepo blogPostRepo;

        public BlogManagerController(ITagRepo tagRepo, IBlogPostRepo blogPostRepo)
        {
            this.tagRepo = tagRepo;
            this.blogPostRepo = blogPostRepo;
        }

        private async Task<IEnumerable<BlogPost>> GetPaginatedBlogPosts(Guid? tagId, int page, int pageSize)
        {
            var blogPosts = tagId.HasValue
                ? await blogPostRepo.GetBlogsByTagAsync(tagId.Value)
                : await blogPostRepo.GetAllAsync();

            return blogPosts.Skip((page - 1) * pageSize).Take(pageSize).ToList();
        }

        [HttpGet]
        [ActionName("List")]
        public async Task<IActionResult> List(Guid? tagId, int page = 1, int pageSize = 6)
        {
            var tags = await tagRepo.GetAllAsync();
            ViewBag.Tags = tags;

            IEnumerable<BlogPost> blogPosts;

            if (tagId.HasValue)
            {
                blogPosts = await blogPostRepo.GetBlogsByTagAsync(tagId.Value);
            }
            else
            {
                blogPosts = await blogPostRepo.GetAllAsync();
            }

            // Calculate total pages
            var totalCount = blogPosts.Count();
            var totalPages = (int)Math.Ceiling((double)totalCount / pageSize);

            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = page;

            // Paginate the results
            var paginatedBlogs = await GetPaginatedBlogPosts(tagId, page, pageSize);

            return View(paginatedBlogs);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var blogPost = await blogPostRepo.GetAsync(id);

            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        [HttpGet("/Admin/BlogManager/Edit/{id}")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var blogPost = await blogPostRepo.GetAsync(id);
            var tagsDomainModel = await tagRepo.GetAllAsync();

            if (blogPost != null)
            {
                var model = new EditBlogPostRequest
                {
                    Id = blogPost.Id,
                    Heading = blogPost.Heading,
                    Title = blogPost.Title,
                    Content = blogPost.Content,
                    Author = blogPost.Author,
                    FeaturedImageURL = blogPost.FeaturedImageURL,
                    UrlHandle = blogPost.UrlHandle,
                    ShortDescription = blogPost.ShortDescription,
                    PublishedDate = blogPost.PublishedDate,
                    Visible = blogPost.Visible,
                    Tags = tagsDomainModel.Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    }),
                    SelectedTags = blogPost.BlogPostTags.Select(x => x.Tag.Id.ToString()).ToArray()
                };

                return View(model);
            }

            return NotFound();
        }

        [HttpPost("/Admin/BlogManager/Update/{id}")]
        public async Task<IActionResult> Update(Guid id, EditBlogPostRequest editBlogPostRequest)
        {
            if (string.IsNullOrWhiteSpace(editBlogPostRequest.Heading) ||
                string.IsNullOrWhiteSpace(editBlogPostRequest.Title) ||
                string.IsNullOrWhiteSpace(editBlogPostRequest.Content) ||
                string.IsNullOrWhiteSpace(editBlogPostRequest.ShortDescription) ||
                string.IsNullOrWhiteSpace(editBlogPostRequest.FeaturedImageURL) ||
                string.IsNullOrWhiteSpace(editBlogPostRequest.UrlHandle))
            {
                TempData["ErrorMessage"] = "All fields are required.";
                return RedirectToAction("Edit", new { id = editBlogPostRequest.Id });
            }

            var blogPostDomainModel = new BlogPost
            {
                Id = id,
                Heading = editBlogPostRequest.Heading,
                Title = editBlogPostRequest.Title,
                Content = editBlogPostRequest.Content,
                Author = editBlogPostRequest.Author,
                ShortDescription = editBlogPostRequest.ShortDescription,
                FeaturedImageURL = editBlogPostRequest.FeaturedImageURL,
                PublishedDate = DateTime.Now,
                UrlHandle = editBlogPostRequest.UrlHandle,
                Visible = editBlogPostRequest.Visible
            };

            var selectedTags = new List<BlogPostTag>();
            foreach (var selectedTagId in editBlogPostRequest.SelectedTags)
            {
                if (Guid.TryParse(selectedTagId, out var tagId))
                {
                    var foundTag = await tagRepo.GetAsync(tagId);

                    if (foundTag != null)
                    {
                        var blogPostTag = new BlogPostTag
                        {
                            TagId = foundTag.Id,
                            Tag = foundTag,
                            BlogPostId = blogPostDomainModel.Id,
                            BlogPost = blogPostDomainModel
                        };

                        selectedTags.Add(blogPostTag);
                    }
                }
            }

            blogPostDomainModel.BlogPostTags = selectedTags;

            var updatedBlog = await blogPostRepo.UpdateAsync(blogPostDomainModel);

            if (updatedBlog != null)
            {
                return RedirectToAction("Edit", new { id = updatedBlog.Id });
            }

            TempData["SuccessMessage"] = "Blog post updated successfully.";
            return RedirectToAction("Edit", new { id = updatedBlog.Id });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var deletedPost = await blogPostRepo.DeleteAsync(id);

            if (deletedPost != null)
            {
                TempData["SuccessMessage"] = "Blog post deleted successfully.";
                return RedirectToAction("List");
            }

            TempData["ErrorMessage"] = "Error deleting the blog post.";

            return RedirectToAction("Edit", new { id });
        }
    }
}

Main/Areas/Admin/Views/BlogManager/Details.cshtml
@model Main.Models.Domain.BlogPost

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container ">
        <h1 class="text-center">Details</h1>
    </div>
</div>

<div>
    <h4>BlogPost</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Heading):
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Heading)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title):
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Content):
        </dt>
        <dd class="col-sm-10">
            @Html.Raw(Model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortDescription):
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FeaturedImageURL):
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FeaturedImageURL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UrlHandle):
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UrlHandle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishedDate):
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author):
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt class="col-sm-2">
            Tags:
        </dt>
        <dd class="col-sm-10">
            @if (Model.BlogPostTags != null && Model.BlogPostTags.Any())
            {
                <div class="d-flex">
                    @foreach (var tag in Model.BlogPostTags)
                    {
                        <span class="badge bg-secondary mx-1">@tag.Tag?.Name</span>
                    }
                </div>
            }
            else
            {
                <p>No tags available.</p>
            }
        </dd>
        
    </dl>
</div>
<div class="d-flex">
    <div >
        <a href="@Url.Action("Edit", "BlogManager", new { area = "Admin", id = Model?.Id })" class="btn btn-dark hover-text-light ">
            Edit
        </a>
    </div> 
    <div class="mx-2">
        <form method="post" action="@Url.Action("Delete", "BlogManager", new { area = "Admin", id = Model?.Id })">
            <button type="submit" class="btn btn-danger hover-text-light">Delete</button>
        </form>
    </div>
    
</div>
<div class="my-5">
    <a href="@Url.Action("List", "BlogManager", new { area = "Admin" })" class="btn btn-secondary">
        Back to List
    </a>
</div>

<div class="mt-5">
    @if (!string.IsNullOrEmpty(ViewBag.SuccessMessage))
    {
        <div class="alert alert-success">
            @ViewBag.SuccessMessage
        </div>
    }
</div>

Main/Areas/Admin/Views/BlogManager/Edit.cshtml
@model Main.Models.ViewModels.EditBlogPostRequest
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container ">
        <h1 class="text-center">Edit BlogPost</h1>
    </div>
</div>

@if (!string.IsNullOrEmpty(TempData["ErrorMessage"] as string))
{
    <div class="alert alert-danger alert-dismissible fade show mt-5 pb-0" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <ul>
            <li>@TempData["ErrorMessage"]</li>
        </ul>
    </div>
}

<div class="container py-5">
    @if (Model != null)
    {
        <form method="post" action="/Admin/BlogManager/Update/{id}">

            <div class="mb-3">
                <label class="form-label">Id</label>
                <input type="text" value="@Model.Id" class="form-control" id="id" name="Id" readonly />
            </div>


            <div class="mb-3">
                <label class="form-label">Heading</label>
                <input type="text" value="@Model.Heading" class="form-control" id="heading" name="Heading" />
            </div>

            <div class="mb-3">
                <label class="form-label">Page Title</label>
                <input type="text" value="@Model.Title" class="form-control" id="pageTitle" name="Title" />
            </div>

            <div class="mb-3">
                <label class="form-label">Content</label>
                <textarea type="text" class=" form-control" id="content" name="Content"> @Model.Content</textarea>
            </div>

            <div class="mb-3">
                <label class="form-label">Short Description</label>
                <input type="text" value="@Model.ShortDescription" class="form-control" id="shortDescription" name="ShortDescription" />
            </div>

            <div class="mb-3">
                <label class="form-label">Upload Image</label>
                <input type="file" id="featuredImageUpload" class="form-control" />
                <img src="" id="featuredImageDisplay" style="display:none; width: 300px" />
            </div>

            <div class="mb-3">
                <label class="form-label">Image URL</label>
                <input type="text" value="@Model.FeaturedImageURL" class="form-control" id="featuredImgURL" name="FeaturedImageURL" readonly/>
            </div>

            <div class="mb-3">
                <label class="form-label">URL Handle</label>
                <input type="text" value="@Model.UrlHandle" class="form-control" id="urlHandle" name="UrlHandle" />
            </div>

            <div class="mb-3" hidden>
                <label class="form-label">Published Date</label>
                <input type="date" value="@Model.PublishedDate.ToString("dd-MM-yyyy")" class="form-control" id="publishedDate" name="PublishedDate" />
            </div>

            <div class="mb-3">
                <label class="form-label">Author</label>
                <input type="text" value="@Model.Author" class="form-control" id="author" name="Author" readonly/>
            </div>

            <div class="mb-3">
                <label class="form-label">Tags</label>
                <select class="form-select" value="@Model.SelectedTags" name="SelectedTags" multiple="multiple">
                    @foreach (var tag in Model.Tags)
                    {
                        <option value="@tag.Value" selected="@Model.SelectedTags.Contains(tag.Value)">@tag.Text</option>
                    }
                </select>
            </div>

            <div class="mb-3 d-flex">
                <button type="submit" class="btn btn-outline-dark hover-text-dark">Update</button>
            </div>
        </form>

    }
    else
    {
        <h1>Model Not Found!</h1>
    }
</div>

@section Scripts {
    <script>

        var editor = new FroalaEditor('#content', {
            imageUploadURL: '/api/images'
        });

        const featuredUpload = document.getElementById('featuredImageUpload');
        const featuredImg = document.getElementById('featuredImgURL');
        const featuredImageDisplay = document.getElementById('featuredImageDisplay');

        async function uploadFeatureImg(e) {
            console.log(e.target.files[0]);

            let data = new FormData();
            data.append('file', e.target.files[0]);

            await fetch('/api/images', {
                method: 'POST',
                headers: {
                    'Accept': '*/*',
                },
                body: data
            }).then(response => response.json())
                .then(result => {
                    featuredImg.value = result.link;
                    featuredImageDisplay.src = result.link;
                    featuredImageDisplay.style.display = 'block';
                });
        }

        featuredUpload.addEventListener('change', uploadFeatureImg);
    </script>
}

Main/Areas/Admin/Views/BlogManager/List.cshtml
@using Main.Models.Domain
@model List<Main.Models.Domain.BlogPost>
@{
ViewData["Title"] = "List";
Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="bg-secondary bg-opacity-10 py-2">
<div class="container">
    <h1 class="text-center">All BlogPosts</h1>
</div>
</div>

<form method="get" class="my-5">
<div class="mb-3">
    <label for="tagDropdown" class="form-label">Select Tag:</label>
    <select id="tagDropdown" class="form-select" name="tagId">
        <option value="">-- Select Tag --</option>
        @foreach (var tag in ViewBag.Tags)
        {
            <option value="@tag.Id">@tag.DisplayName</option>
        }
    </select>
</div>
<div class="mb-3">
    <label for="orderByDropdown" class="form-label">Order by:</label>
    <select id="orderByDropdown" class="form-select" name="orderBy">
        <option value="Heading" selected>Heading</option>
        <option value="Id">ID</option>
    </select>
</div>
<button type="submit" class="btn btn-dark">Filter</button>
</form>

<div class="container">
@if (Model != null && Model.Any())
{
    var orderBy = Context.Request.Query["orderBy"];
    var orderedPosts = OrderBlogPosts(Model, orderBy);
        var count = 1;

    <table class="table table-striped mt-5">
        <thead>
            <tr>
                <td class="fw-bold">#</td>
                <td class="fw-bold">ID</td>
                <td class="fw-bold">HEADING</td>
                <td class="fw-bold">TAGS</td>
                <td class="fw-bold"></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var post in orderedPosts)
            {
                <tr>
                    <td class="fw-bold">@(count++)</td>
                    <td>@post.Id</td>
                    <td>@post.Heading</td>
                    <td>
                        <div class="d-flex flex-wrap">
                            @foreach (var tag in post.BlogPostTags)
                            {
                                <span class="badge bg-secondary mx-1 my-2">@tag.Tag.DisplayName</span>
                            }
                        </div>
                    </td>
                    <td>
                        <a href="@Url.Action("Details", "BlogManager", new { area = "Admin", id = post.Id })" class="btn btn-light btn-outline-dark hover-text-primary">
                            <i class="bi bi-info-circle"></i>
                            Details
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <!-- Pagination -->
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center mt-4">
            @for (int i = 1; i <= ViewBag.TotalPages; i++)
            {
                <li class="page-item @(i == ViewBag.CurrentPage ? "active" : "")">
                    <a class="page-link bg-dark text-light" href="?page=@i&tagId=@Context.Request.Query["tagId"]&orderBy=@Context.Request.Query["orderBy"]">@i</a>
                </li>
            }
        </ul>
    </nav>
}
else
{
    <h3 class="text-center mt-5">No blog posts found..</h3>
}
</div>

@functions {
private IEnumerable<Main.Models.Domain.BlogPost> OrderBlogPosts(List<Main.Models.Domain.BlogPost> posts, string orderBy)
{
    switch (orderBy)
    {
        case "Heading":
            return posts.OrderBy(post => post.Heading);
        case "Id":
            return posts.OrderBy(post => post.Id);
        default:
            return posts;
    }
}
}